repository: fmpaci/fmpaci.github.io
version: 1
name: Federico Paci
email: fmpaci88@gmail.com
darkmode: false
trigger_darkmode:
  start_light: '08'
  start_dark: '18'
last_updated_time: 15th Nov 2023

github_username: fmpaci
linkedin_username: fpaci

about_title: About Me
about_profile_image: images/me.jpg
about_content: |
  - I'm Federico Paci and I'm living in Mendoza, Argentina.
  - My interests are around the world of Data such as **Data Engineering**, **Data Modeling**, **Data Orchestration**

  - My CV: <br>
  -- <a href="https://fmpaci.github.io/files/CV_Federico_Paci_eng.pdf" target="_blank"><b>CV English  </b></a><br>
  -- <a href="https://fmpaci.github.io/files/CV_Federico_Paci_EA.pdf" target="_blank"><b>ATS Friendly</b></a><br>
  -- <a href="https://fmpaci.github.io/files/CV_Federico_Paci_spa.pdf" target="_blank"><b>CV Spanish</b></a>
    
  - Currently I'm studying best practices of DAMA organization to get better performance, governance and metadata management.
  
  - I'm a self-motivated Data Engineer with +5 years of experience in data warehouse, ETL Development, data management. 
  Collaborates effectively with multi-functional roles to identify and leverage areas for improvement in data systems.
  Bringing comprehensive understanding of warehouse operations and documentation needs.

#more_content: |
#    More content here

footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lib/
  - scripts/
  - docker-compose.yml




