repository: fmpaci/fmpaci.github.io
version: 1
name: Federico Paci
email: fmpaci88@gmail.com
darkmode: false
trigger_darkmode:
  start_light: '08'
  start_dark: '18'
last_updated_time: 15th Nov 2023

github_username: fmpaci
linkedin_username: fpaci

about_title: About Me
about_profile_image: images/me.jpg
about_content: |
  **CV: [PDF](https://fmpaci.github.io/files/CV-Federico.Paci.pdf)**

  I'm Federico Paci and I'm living in Mendoza, Argentina.
  My interests are around the world of Data such as **Data Engineering**, **Data Modeling**, **Data Orchestation**
  
more_content: |
    More content here

footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lib/
  - scripts/
  - docker-compose.yml
