repository: alirezadizaji/alirezadizaji.github.io
version: 1
name: Federico Paci
email: fmpaci88@gmail.com
darkmode: false
trigger_darkmode:
  start_light: '05'
  start_dark: '16'
last_updated_time: 15th Nov 2023
github_username: fmpaci
linkedin_username: fpaci
about_title: About Me
about_profile_image: images/me.jpeg
about_content: |
  **CV: [PDF](https://fmpaci.github.io/files/files/CV-Federico.Paci.pdf)**

  I'm Federico Paci and I'm living in Mendoza, Argentina.
  My interests are around the world of Data such as **Data Engineering**, **Data Modeling**, **Data Orchestation**, and **Explainable Machine Learning**.
more_content: |
    More content here



    - **Watching movies**
    - **Travelling and nature**
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Quebec Artificial Intelligence Institute (MILA)
        sub_title: Graduate Research Assistant
        caption: Sep. 2023 - present
        description: ''
      - layout: left
        title: AI-Med
        sub_title: R&D scientist
        caption: April 2021 - present
        link: https://aimed-sharif.ir/
        description: |
          AI-Med is a multidisciplinary research consortium **utilizing artificial intelligence
          technologies to improve the quality and accuracy of digital health services**.
          since April 2021, I joined as **research and development scientist** here where
          we have designed a wide-range of deep-learning experiments (via Pytorch) to provide
          better **detection** and **localization** of abnormalities for **mammography screening**.
          our methods have reached and even gone beyond the state-of-the-art algorithms on **public dataset (DDSM)**.
          in order to maintain our results same for the **in-private dataset**, we are currently
          developing **weakly-supervised methods** to more precisely label and generate ground-truth ROIs for them.
          Moreover, we have designed several side tools to get real-time feedbacks from experienced radiologists for labeling. 
      - layout: left
        title: Sharif University of Technology
        sub_title: Research Assistant
        caption: August 2020 - March 2021
        description: |
          I joined [**DML lab**](http://dml.ce.sharif.edu/dmlsite/) as a **Research assistant** where I was working
          on the impact of **contrastive learning** approaches on **deep reinforcement-learning** algorithms.
          to be more specific, I implemented [**CURL**](https://arxiv.org/pdf/2004.04136.pdf?ref=https://githubhelp.com) 
          and [**SIMCLR**](https://arxiv.org/pdf/2002.05709.pdf) (via Pytorch) algorithms to improve movement of an agent
          within Maze environment.
      - layout: left
        title: Sharif University of Technology
        sub_title: Teaching Assistant
        caption: Februrary 2019 - July 2021
        description: |
          since my second semester, I have collaborated as a **teaching assistant** with several
          faculty members of **computer engineering department**. all courses that I have contributed are listed below:

          **Spring 2021**
          - Machine learning (M.Sc. course), Dr. Rohban
          - Modern information retrival, Dr. Soleymani


          **Fall 2020**
          - Artificial intelligence, Dr. Rohban
          - Linear algebra, Prof. Rabiee


          **spring 2020**
          - Computer architecture, Prof. Asadi
          - Data structures and algorithms, Dr. Safarnejad broujeni


          **spring 2019**
          - Advanced programming, Mr. Hatami
  - title: Education
    layout: list
    content:
      - layout: left
        title: Sharif University of Technology
        sub_title: B.Sc. Computer Engineering
        caption: Sep. 2017-Sep. 2022
        description: |
          GPA: 17.90/20 (**last six semesters: 18.51/20**)

          **Related courses**

          Convolutional neural networks for visual recognition (audited, online Stanford),
          machine learning (audited, online Stanford), artificial intelligence, linear algebra,
          data structures and algorithms, introduction to bioinformatics, modern information retrieval,
          design of algorithms, probability and statistics, discrete structures.
      - layout: left
        title: Allame Amini highschool
        sub_title: Diploma
        caption: 2013-2017
        description: |
          I received my Diploma in Mathematics and Physics from Allame Amini highschool,
          where I was ranked 24th out of 350k students in Iranian nationwide mathematics
          exam (Konkur).
  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in science and technology, some of my other hobbies are:
        - Reading books: I am a big fan of Fantasy books, and mostly
        spend my leisure time reading them in English. Sometimes I really feel sick of this world, and I'd like to put my mind away from it and live through the others. Besides, for me the most joyful and cheapest way of journeying is reading books:
          - J.R.R Tolkien's Valar, Numenor, and Middle-earth history: I have read the <i> Silmarillion </i>, <i> Unfinished Tales </i>, <i> Hobbit </i>, and <i> Lord of the Rings </i> series of sir Tolkien, traveling through the time, and understanding many things
          like the instinct consequences of envying, seeking the immortality, and forging evil wills. In addition, fates, reasons behind beings of all creatures, and our path in our lives. Seems like we are descendants of the Men, but I prefer to be from Eldar races :(.
          - J.K. Rowling's Harry Potter series: I have read all seven books of the Harry Potter series, understanding again the consequences of seeking immortality, creating your own enemies by oppression, and the hidden power of Love.
          - Andrzej Sapkowski's Witcher series: ...
        - Watching movies
        - Travelling and nature
footer_show_references: false
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lib/
  - scripts/
  - docker-compose.yml
